name: Compile to Extension

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - name: Archive Package
        uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          path: "dist"
          filename: "release.zip"
          exclusions: "*.git* /*node_modules/* .editorconfig"
      - uses: Klemensas/action-autotag@stable
        name: Create tag
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Release Archive
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
